# Generated by Django 3.0.2 on 2020-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('expense_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expense_type', models.CharField(choices=[('invest', 'Invest'), ('non_invest', 'Non_Invest')], max_length=45)),
                ('expense_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-expense_date',),
            },
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('received_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-received_date',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('transaction_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('monthly', 'Monthly'), ('additional', 'Additional'), ('others', 'Others')], max_length=45)),
                ('transaction_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-transaction_date',),
            },
        ),
    ]
