# Generated by Django 3.0.2 on 2020-01-22 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20200117_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='expense_guid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=45),
        ),
        migrations.AddField(
            model_name='incometransaction',
            name='income_guid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=45),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_guid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=45),
        ),
    ]
