# Generated by Django 3.0.2 on 2020-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_auto_20200122_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
