# Generated by Django 3.0.2 on 2020-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_auto_20200122_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='expense_date',
            field=models.DateField(blank=True, db_index=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='received_date',
            field=models.DateField(blank=True, db_index=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
