# Generated by Django 3.0.2 on 2020-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='short_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
