# Generated by Django 3.0.2 on 2020-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200122_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='Add your designation', max_length=255, null=True),
        ),
    ]
