# Generated by Django 3.0.2 on 2020-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200122_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
